---
title: "Nifty but forgettable functions"
author: "Brian"
date: '2018-10-01'
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  fig.path = "img/brian-nifty-but-forgettable/"
)
```

## Sampling functions

Can be used for planning experiments (e.g. particularly useful in choosing plots & tank numbers).

```{r}
X <- 1:6
sample(X)
sample(X,1)

# five random numbers between 0 and 1
runif(n=5,min=0,max=1)

# e.g. generate random points on the cartesian plane
# useful for generating preliminary datasets (i.e. simulate measurements)
coords <- data.frame(x=runif(100,0,10),y=runif(100,0,10))
plot(coords$x, coords$y)
```

## Repeat function

Useful for generating and annotating dataframes.

```{r}
E <- rep(c("M","F"),each = 3)
E
G <- rep(c("M","F"),c(2,4))
G
```

## Loops

```{r}
money <- 100
for (i in 1:50){
  if(sample(1:6,1)%in%1:3){money = money + 10 }else{ money <- money -10}
}
money

# basic for-loop without subsitutions designated just runs the function for the designated number
for (i in 1:3) {print('hi')}
for (i in 1:2) {print('hi')}
```

